logging:
  level:
    org.springframework: info

currency-service:
  url:
    - https://currencyservice.com
    - https://currencyservice.uk
    - https://currencyservice.co.kr
  username: userName
  key: userKey