logging:
  level:
    org.springframework: debug

spring:
  profiles:
    active: dev

currency-service:
  url:
    - https://currencyservice.com
    - https://currencyservice.uk
    - https://currencyservice.co.kr
  username: userName
  key: userKey

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

management:
  endpoints:
    web:
      exposure:
        include: health, metrics